write_jsonl: true

load_config:
  path_name: Helsinki-NLP/europarl
  name: de-en
  split: train
  #max_examples: 1000

norm_config:
  changes:
    - strip_edges
    - remove_control_chars
    - collapse_whitespace
    - normalize_unicode_quotes

filter_config:
  predicates:
    - is_blank
    - [is_too_short, {min: 10}]
    - [is_too_long, {max: 1500}]
    - contains_url
    - contains_email
    - contains_control_chars
    - contains_invisible_format_chars
    - has_odd_number_of_quotes
    - has_unbalanced_brackets
  pair_predicates:
    - [bad_length_ratio, {min: 0.33, max: 3}]
    - are_equal

tokenize_config:
  tokenizer_model_name: Helsinki-NLP/opus-mt-de-en
  max_seq_len: 250

map_config:
  src_lang: de
  tgt_lang: en
