write_jsonl: true

download_cfg:
  dataset: IWSLT/iwslt2017
  config: iwslt2017-de-en
  split: train
  source_format: hf_parquet
  revision: b2dcd74c28e4544eb5c9bb76ace449ea26bbe909

norm_cfg:
  changes:
    - strip_edges
    - remove_control_chars
    - collapse_whitespace
    - normalize_unicode_quotes

filter_cfg:
  predicates:
    - is_blank
    - [is_too_short, {min: 10}]
    #- [is_too_long, {max: 300}]
    - contains_url
    - contains_email
    - contains_control_chars
    - contains_invisible_format_chars
    - has_odd_number_of_quotes
    - has_unbalanced_brackets
  pair_predicates:
    - [bad_length_ratio, {min: 0.33, max: 3}]
    - are_equal

tokenize_cfg:
  tokenizer_model_name: Helsinki-NLP/opus-mt-de-en
  max_src_len: 250

map_cfg:
  src_lang: de
  tgt_lang: en
